### ISSUE TITLE
[Bug]: The background command workers will panic in the integration test "recovery_after_compaction"

### ISSUE THREAD

**Issue by Phoenix500526** [datenlord/Xline#285]
### Description about the bug

As the title described, a background cmd worker will panic when it received a `CEEvent::Snapshot`. The log is pasted down below.

### Version

0.4.0 (Default)

### Relevant log output

```shell
0.433941159s DEBUG server_recovery::common::test_cmd: S4 after sync cmd(Put(6) - "7"), index: 7
thread 'rt-S0' panicked at 'assertion failed: `(left == right)`
  left: `14`,
 right: `15`   
', /home/jiawei/Xline/curp/src/server/cmd_worker/mod.rs:131:21
stack backtrace:
   0: rust_begin_unwind
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/panicking.rs:64:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/panicking.rs:199:5
   4: curp::server::cmd_worker::cmd_worker::{{closure}}
             at ./src/server/cmd_worker/mod.rs:131:21
   5: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at /home/jiawei/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/tokio-1.26.0/src/runtime/task/core.rs:223:17
   6: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /home/jiawei/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/tokio-1.26.0/src/loom/std/unsafe_cell.rs:14:9
   7: tokio::runtime::task::core::Core<T,S>::poll
             at /home/jiawei/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/tokio-1.26.0/src/runtime/task/core.rs:212:13
   8: tokio::runtime::task::harness::poll_future::{{closure}}
             at /home/jiawei/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/tokio-1.26.0/src/runtime/task/harness.rs:476:19
   9: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/panic/unwind_safe.rs:271:9
  10: std::panicking::try::do_call
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:483:40
  11: __rust_try
  12: std::panicking::try
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:447:19
  13: std::panic::catch_unwind
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panic.rs:137:14
  14: tokio::runtime::task::harness::poll_future
             at /home/jiawei/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/tokio-1.26.0/src/runtime/task/harness.rs:464:18
  15: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /home/jiawei/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/tokio-1.26.0/src/runtime/task/harness.rs:198:27
  16: tokio::runtime::task::harness::Harness<T,S>::poll
             at /home/jiawei/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/tokio-1.26.0/src/runtime/task/harness.rs:152:15
  17: tokio::runtime::task::raw::poll
             at /home/jiawei/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/tokio-1.26.0/src/runtime/task/raw.rs:255:5
  18: tokio::runtime::task::raw::RawTask::poll
             at /home/jiawei/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/tokio-1.26.0/src/runtime/task/raw.rs:200:18
  19: tokio::runtime::task::LocalNotified<S>::run
             at /home/jiawei/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/tokio-1.26.0/src/runtime/task/mod.rs:394:9
  20: tokio::runtime::scheduler::multi_thread::worker::Context::run_task::{{closure}}
             at /home/jiawei/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/tokio-1.26.0/src/runtime/scheduler/multi_thread/worker.rs:487:21
  21: tokio::runtime::coop::with_budget
             at /home/jiawei/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/tokio-1.26.0/src/runtime/coop.rs:107:5
  22: tokio::runtime::coop::budget
             at /home/jiawei/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/tokio-1.26.0/src/runtime/coop.rs:73:5
  23: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
             at /home/jiawei/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/tokio-1.26.0/src/runtime/scheduler/multi_thread/worker.rs:463:9
  24: tokio::runtime::scheduler::multi_thread::worker::Context::run
             at /home/jiawei/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/tokio-1.26.0/src/runtime/scheduler/multi_thread/worker.rs:433:24
  25: tokio::runtime::scheduler::multi_thread::worker::run::{{closure}}
             at /home/jiawei/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/tokio-1.26.0/src/runtime/scheduler/multi_thread/worker.rs:406:17
  26: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /home/jiawei/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/tokio-1.26.0/src/macros/scoped_tls.rs:61:9
  27: tokio::runtime::scheduler::multi_thread::worker::run
             at /home/jiawei/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/tokio-1.26.0/src/runtime/scheduler/multi_thread/worker.rs:403:5
  28: tokio::runtime::scheduler::multi_thread::worker::Launch::launch::{{closure}}
             at /home/jiawei/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/tokio-1.26.0/src/runtime/scheduler/multi_thread/worker.rs:365:45
  29: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
             at /home/jiawei/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/tokio-1.26.0/src/runtime/blocking/task.rs:42:21
  30: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at /home/jiawei/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/tokio-1.26.0/src/runtime/task/core.rs:223:17
  31: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /home/jiawei/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/tokio-1.26.0/src/loom/std/unsafe_cell.rs:14:9
  32: tokio::runtime::task::core::Core<T,S>::poll
             at /home/jiawei/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/tokio-1.26.0/src/runtime/task/core.rs:212:13
  33: tokio::runtime::task::harness::poll_future::{{closure}}
             at /home/jiawei/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/tokio-1.26.0/src/runtime/task/harness.rs:476:19
  34: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/panic/unwind_safe.rs:271:9
  35: std::panicking::try::do_call
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:483:40
  36: __rust_try
  37: std::panicking::try
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:447:19
  38: std::panic::catch_unwind
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panic.rs:137:14
  39: tokio::runtime::task::harness::poll_future
             at /home/jiawei/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/tokio-1.26.0/src/runtime/task/harness.rs:464:18
  40: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /home/jiawei/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/tokio-1.26.0/src/runtime/task/harness.rs:198:27
  41: tokio::runtime::task::harness::Harness<T,S>::poll
             at /home/jiawei/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/tokio-1.26.0/src/runtime/task/harness.rs:152:15
  42: tokio::runtime::task::raw::poll
             at /home/jiawei/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/tokio-1.26.0/src/runtime/task/raw.rs:255:5
  43: tokio::runtime::task::raw::RawTask::poll
             at /home/jiawei/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/tokio-1.26.0/src/runtime/task/raw.rs:200:18
  44: tokio::runtime::task::UnownedTask<S>::run
             at /home/jiawei/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/tokio-1.26.0/src/runtime/task/mod.rs:431:9
  45: tokio::runtime::blocking::pool::Task::run
             at /home/jiawei/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/tokio-1.26.0/src/runtime/blocking/pool.rs:159:9
  46: tokio::runtime::blocking::pool::Inner::run
             at /home/jiawei/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/tokio-1.26.0/src/runtime/blocking/pool.rs:511:17
  47: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
             at /home/jiawei/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/tokio-1.26.0/src/runtime/blocking/pool.rs:469:13
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Phoenix500526** [comment]
The root cause is that we make a wrong assertion in the `cmd_worker`. The `last_included_index` of a snapshot is equal to the `log.last_exe` but not the `log.last_as`.  We only had one index named `last_applied` in our log before we introduced the curp log compaction feature. Therefore, this assertion was right at that time.  We renamed the `last_applied` to `last_as` and added a new field named `last_exe` in pr #218.
